
    <body>
      <br/><br/><br/><br/><br/><br/>
    	<div class="container">
    	  <h2 style="border-bottom:1px solid #6126AC; width:auto;"><span>Description </span></h2>
    	  	
    	  	<div class="panel-body">
    	  		<div class="col-md-4">
    	  			<img src="<?php  echo $profil->photo?>" alt="" class="img-thumbnail" style="width: 150px; height: 150px;">
    	  			<p>
    	  			<?php 
    	  			
            			echo "nom : $profil->nom <br/>";
            			echo "adresse : $profil->adresse <br/>";
            			echo "portable : $profil->portable <br/>";
            			echo "email : $profil->email <br/>";
            		?>
            		<br/>
            		</p>
            	</div>
            	<div class="col-md-8">
            		<p>
            		<?php
            			echo "Presentation : $profil->presentation <br/>";
            		?>
            		</p>
            	</div>
            	<div>
            			<a  class="btn btn-primary pull-right" href="<?php  echo $this->url('gestprofil', array('action'=>'edit', 'id'=> $profil->id));?>">Editer</a>
            		<br/>
            	</div>
            </div>
            </div>
       

          
          <div class="container">
           <h2 style="border-bottom:1px solid #6126AC; width:auto;"><span>Mes souhaits </span></h2>
            <div class="panel-body">
              <table class="table-condensed table-responsive table">
        <thead>
          <tr>
            <th>#</th>
            <th>Libelle</th>
            <th>Description</th>
            <th>Prix</th>
          </tr>
        </thead>
        <tbody>
        
        <?php
        
          	foreach ($cadeaux as $cadeau)
          	{
          		echo "<tr>";
          		echo "<td></td>";
          		echo "<td> $cadeau->libelle</td>";
          		echo "<td> $cadeau->description</td>";
          		echo "<td>$cadeau->prix</td>";
          		echo "<td></td>";
          		echo "</tr>";
          	}
          	
            ?>
                  </tr>
        </tbody>
      </table>
     
          <a class="btn btn-primary pull-right" href="<?php echo $this->url('gestcadeau', array('action'=>'add', 'id' => $profil->id, $cadeaux));?>">Modifier</a>
        
          <br/>
          </div>
          </div>
     
  </body>