<?php

$title = 'Supprimer un souhait';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Etes vous sur de vouloir supprimer
    '<?php echo $this->escapeHtml($cadeau->libelle); ?>' ?
  </p>
<?php

$url = $this->url('gestcadeau', array( 'action' => 'delete','id' => $this->id,'id2' => $this->id2));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="submit" class="btn btn-default" name="del" value="Oui" />
    <input type="submit" class="btn btn-default" name="del" value="Non" />
</div>
</form>