<?php 
	$this->headScript()->prependFile($this->basePath() . '/js/ini.js');
?>


</head>
<body>


<div class="global">
<div id="slider">
    <div id="flexslider">
        <ul class="slides clearfix">
            <li>
                <img alt="" src="<?php echo $this->basePath('img/picture1.png');?>">
                <div class="flex-caption">
                    <div class="flex-box1">
                        <p class="title1">UN ANNIVERSAIRE ?</p>
                        <p class="title2">CREEZ UNE CAGNOTTE !</p>
                    </div>
                    <div class="flex-box2">
                        <p>Organisez le cadeau commun pour un anniversaire et reunissez simplement l'argent des participants</p>
                    </div>
                </div>
            </li>
            <li>
                <img alt="" src="<?php echo $this->basePath('img/picture2.jpg');?>">
                <div class="flex-caption">
                    <div class="flex-box1">
                        <p class="title1">OFFREZ DES CADEAUX</p>
                        <p class="title2">RIEN DE PLUS SIMPLE</p>
                    </div>
                    <div class="flex-box2">
                        <p>J'offre a mon ami(e) un cadeau commun dont elle se souviendra longtemps</p>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>                            
    <!--content-->
    <div class="container padBot">
        <div class="row">
             <section class="span12 border1">
                <div class="row">
                    <article class="span7">
                        <h2><span>Bienvenu sur KDO</span></h2>
                        <h4>Comment ca marche ?</h4>
                        <p class="margBot">Creez gratuitement et en quelques clics votre cagnotte sur KDO. Invitez vos amis a participer. Collectez l'argent des participations en toute securite.
											Lorsque la cagnotte est terminee, depensez-la selon vos envies chez nos partenaires (c'est gratuit !), en demandant un virement ou en l'offrant directement a son destinataire.</p>
                        <a href="#" class="btn btn-info">INformation</a>
                    </article>
                    <article class="span5">
                        <h3>Quels services ?</h3>
                        <ul class="list5">
                            <li>
                                <figure><img alt="" src="<?php echo $this->basePath('img/birthday.png');?>"></figure>
                                <div class="extra-wrap">
                                    <a href="#">Pour les anniversaires</a>
                                    <p>L'anniversaire de votre enfant arrive a grands pas et vous vous creusez la tete... demandez de l'aide a vos proche !</p>
                                </div>
                            </li>
                            <li>
                                <figure><img alt="" src="<?php echo $this->basePath('img/wedding.png');?>"></figure>
                                <div class="extra-wrap">
                                    <a href="#">Pour les mariages</a>
                                    <p>Meme si c'est votre plus grosse erreur, essayer au moins d'avoir des cadeaux a partager pour le jour du divorce !</p>
                                </div>
                            </li>
                            <li>
                                <figure><img alt="" src="<?php echo $this->basePath('img/other.png');?>"></figure>
                                <div class="extra-wrap">
                                    <a href="#">Pour d'autres activites </a>
                                    <p>Marre de la France... offrez vous un voyage grace a l'aide de vos amis !</p>
                                </div>
                            </li>
                        </ul>
                    </article>
                </div>
             </section>
             <article class="span12 slogan">
                <div class="clearfix">
                    <h2>Lancez vous !</h2>
                    <h5><span>Il n'y a rien de plus simple, tout ce fait en quelque cliques</span></h5>
                </div>
                <a href="#" class="btn btn-primary pull-right">Creer un evenement </a>
             </article>
             <section class="span12">
                <div class="row">
                    <article class="span8">
                        <h3>On parle de nous !</h3>
                        <div class="row">
                          
                            <div class="thumb-pad6 span4">
                                <div class="thumbnail">
                                    <figure><div class="badge"><p>95%</p></div><img src="<?php echo $this->basePath('img/Client.png');?>" alt=""></figure>
                                    <div class="caption">
                                        <a href="#">Nos clients sont satisfaits</a>
                                        <p>95% de nos clients sont satisfaits de KDO et reutilise le service plusieurs fois dans l'annee... Faites comme eux et lancez vous ! </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </article>
                    <article class="span4 testim-box">
                        <h3>Temoignages</h3>
                        <div class="list_carousel responsive clearfix">
                            <ul id="foo">
                                <li>
                                    <figure><img alt="" src="<?php echo $this->basePath('img/man.png');?>"></figure>
                                    <div class="caption">
                                        <h5>ROGER MORRAY</h5>
                                        <h6>Babteme</h6>
                                        <p>J'ai cree une cagnotte sur KDO intitulee "Pour le bapteme du p'tit dernier"</p>
                                    </div>
                                    <p> il y a un peu plus d'un mois, et j'ai reussi a motiver toute la famille pour y participer !</p>
                                </li>
                                <li>
                                    <figure><img alt="" src="<?php echo $this->basePath('img/girl.png');?>"></figure>
                                    <div class="caption">
                                        <h5>MARTINE MARTIN</h5>
                                        <h6>Anniversaire</h6>
                                        <p>Ma soeur a fete recemment ses 28 ans.</p>
                                    </div>
                                    <p>Nous avons fait appel a KDO pour l'organisation d'un cadeau commun pour notre plus grand bonheur.</p>
                                </li>
                            </ul>
                                <a id="prev" class="prev" href="#"></a>
                                <a id="next" class="next" href="#"></a>
                        </div>
                    </article>
                </div>
             </section>
         </div>
     </div>
</div>


</body>
</html>
