
    <body>
<br/><br/><br/><br/><br/><br/>
    	<div class="container">
    	  	<h2 style="border-bottom:1px solid #6126AC; width:auto;"><span> Je suis invite a : </span></h2>

      <div class="panel-body">
        <table class="table-condensed table-responsive table">
        <thead>
          <tr>
            <th>Evenement </th>
            <th>Date</th>
            <th>Destinataire</th>
            <th>Description Cadeau</th>
            <th>Prix Cadeau</th>
             <th>Somme recoltee</th>
          </tr>
        </thead>
        <tbody>
       
       
        </tbody>
      </table>
        </div>
      

      </div>
 </div>
    </div> <!-- /container -->


    