<?php

$title = 'Ajouter une personne';
$this->headTitle($title);

?>
<body>

<br/><br/><br/><br/><br/><br/>
<div class="container">
    <h2 style="border-bottom:1px solid #6126AC; width:auto;"><span> Ajouter une personne a l'evenement </span></h2>
    
    <br/><br/><br/>
    <a href="<?php echo $this->url('gestevenement', array('action'=>'index'));?>" class="btn btn-primary pull-right">Retour evenement </a>
</div>

</body>