<?php

$title = 'Supprimer un evenement';
$this->headTitle($title);

?>
<body>

<br/><br/><br/><br/><br/><br/>
<div class="container">
    <h2 style="border-bottom:1px solid #6126AC; width:auto;"><span> Supprimer l'evenement </span></h2>
    <h3>Vous avez supprimer l'evenement.</h3>
    <br/><br/><br/>
    <a href="<?php echo $this->url('gestevenement', array('action'=>'index'));?>" class="btn btn-primary pull-right">Retour evenement </a>
</div>

</body>